CREATE SCHEMA IF NOT EXISTS CST AUTHORIZATION SA;
CREATE SCHEMA IF NOT EXISTS EMP AUTHORIZATION SA;

CREATE TABLE CST.CUSTOMERS (

	CUSTOMER_ID    BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME     VARCHAR(20)  NOT NULL,
	LAST_NAME      VARCHAR(30)  NOT NULL,
	PHONE_NUMBER   VARCHAR(15)  NOT NULL,
	EMAIL_ADDRESS  VARCHAR(100) NOT NULL,
	BIRTH_DATE     TIMESTAMP        NULL,
	CREATED_DATE   TIMESTAMP    NOT NULL  DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE  TIMESTAMP        NULL
);

CREATE TABLE CST.CUSTOMER_ADDRESSES (

	ADDRESS_ID      INTEGER      NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CUSTOMER_ID     BIGINT           NULL,
	STREET_NUMBER   INTEGER      NOT NULL,
	STREET_NAME     VARCHAR(50)  NOT NULL,
	CITY_NAME       VARCHAR(30)  NOT NULL,
	STATE_NAME      VARCHAR(20)  NOT NULL,
	COUNTRY_NAME    VARCHAR(20)  NOT NULL,
	ZIP_CODE        VARCHAR(10)  NOT NULL,
	CREATED_DATE    TIMESTAMP    NOT NULL  DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE   TIMESTAMP        NULL
);
--====================================================================--

CREATE TABLE EMP.EMPLOYEES (

	EMPLOYEE_ID    BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME     VARCHAR(20)  NOT NULL,
	LAST_NAME      VARCHAR(30)  NOT NULL,
	PHONE_NUMBER   VARCHAR(15)  NOT NULL,
	EMAIL_ADDRESS  VARCHAR(100) NOT NULL,
	BIRTH_DATE     TIMESTAMP        NULL,
	CREATED_DATE   TIMESTAMP    NOT NULL  DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE  TIMESTAMP        NULL
);

CREATE TABLE EMP.EMPLOYEE_ADDRESSES (

	ADDRESS_ID      INTEGER      NOT NULL AUTO_INCREMENT PRIMARY KEY,
	EMPLOYEE_ID     BIGINT           NULL,
	STREET_NUMBER   INTEGER      NOT NULL,
	STREET_NAME     VARCHAR(50)  NOT NULL,
	CITY_NAME       VARCHAR(30)  NOT NULL,
	STATE_NAME      VARCHAR(20)  NOT NULL,
	COUNTRY_NAME    VARCHAR(20)  NOT NULL,
	ZIP_CODE        VARCHAR(10)  NOT NULL,
	CREATED_DATE    TIMESTAMP    NOT NULL  DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE   TIMESTAMP        NULL
);



