CREATE SCHEMA IF NOT EXISTS CST AUTHORIZATION SA;
CREATE SCHEMA IF NOT EXISTS EMP AUTHORIZATION SA;

CREATE TABLE IF NOT EXISTS CST.USERS (

	USER_ID        BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USER_NAME      VARCHAR(20)  NOT NULL,
	PASSWORD       VARCHAR(256) NOT NULL,
	LOCKED         BOOLEAN      NOT NULL  DEFAULT FALSE,
	ENABLED        BOOLEAN      NOT NULL  DEFAULT TRUE,
	FAILED_ATTEMPT INT          NOT NULL  DEFAULT 0,
	LOCK_TIME      TIMESTAMP        NULL,
	CREATED_DATE   TIMESTAMP    NOT NULL  DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE  TIMESTAMP        NULL
);
--====================================================================--
CREATE TABLE IF NOT EXISTS CST.CUSTOMERS (

	CUSTOMER_ID    BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USER_ID        BIGINT           NULL,
  FIRST_NAME     VARCHAR(20)  NOT NULL,
	LAST_NAME      VARCHAR(30)  NOT NULL,
	PHONE_NUMBER   VARCHAR(15)  NOT NULL,
	EMAIL_ADDRESS  VARCHAR(100) NOT NULL,
	BIRTH_DATE     TIMESTAMP        NULL,
	CREATED_DATE   TIMESTAMP    NOT NULL  DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE  TIMESTAMP        NULL
);

CREATE TABLE IF NOT EXISTS CST.CUSTOMER_ADDRESSES (

	ADDRESS_ID      INTEGER      NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CUSTOMER_ID     BIGINT           NULL,
	STREET_NUMBER   INTEGER      NOT NULL,
	STREET_NAME     VARCHAR(50)  NOT NULL,
	CITY_NAME       VARCHAR(30)  NOT NULL,
	STATE_NAME      VARCHAR(20)  NOT NULL,
	COUNTRY_NAME    VARCHAR(20)  NOT NULL,
	ZIP_CODE        VARCHAR(10)  NOT NULL,
	CREATED_DATE    TIMESTAMP    NOT NULL  DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE   TIMESTAMP        NULL
);
--====================================================================--

CREATE TABLE IF NOT EXISTS EMP.EMPLOYEES (

	EMPLOYEE_ID    BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME     VARCHAR(20)  NOT NULL,
	LAST_NAME      VARCHAR(30)  NOT NULL,
	PHONE_NUMBER   VARCHAR(15)  NOT NULL,
	EMAIL_ADDRESS  VARCHAR(100) NOT NULL,
	BIRTH_DATE     TIMESTAMP        NULL,
	CREATED_DATE   TIMESTAMP    NOT NULL  DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE  TIMESTAMP        NULL
);

CREATE TABLE IF NOT EXISTS EMP.EMPLOYEE_ADDRESSES (

	ADDRESS_ID      INTEGER      NOT NULL AUTO_INCREMENT PRIMARY KEY,
	EMPLOYEE_ID     BIGINT           NULL,
	STREET_NUMBER   INTEGER      NOT NULL,
	STREET_NAME     VARCHAR(50)  NOT NULL,
	CITY_NAME       VARCHAR(30)  NOT NULL,
	STATE_NAME      VARCHAR(20)  NOT NULL,
	COUNTRY_NAME    VARCHAR(20)  NOT NULL,
	ZIP_CODE        VARCHAR(10)  NOT NULL,
	CREATED_DATE    TIMESTAMP    NOT NULL  DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE   TIMESTAMP        NULL
);



